apiVersion: v1
kind: Template
metadata:
  name: simple-java-maven-app
parameters:
- name: APP_NAME
  displayName: Application Name
  required: true
  value: simple-java-maven-app
- name: GIT_URL
  displayName: Source URL
  required: true
  value: https://github.com/nathansevugan/springboot-echo-service.git
- name: GIT_REF
  displayName: Source Ref
  required: true
  value: master
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      app: ${APP_NAME}
    name: ${APP_NAME}
    namespace: dev
  spec:
    lookupPolicy:
      local: false

- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: ${APP_NAME}-build
  spec:
    source:
      git:
        uri: https://github.com/nathansevugan/simple-java-maven-app.git
    strategy:
      jenkinsPipelineStrategy:
        jenkinsfilePath: ./jenkins/Jenkinsfile
      successfulBuildsHistoryLimit: 5
      triggers:
        type: ImageChange


